---
title: Ardika Rommy Sanjaya
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    comments: 'true'
name: Ardika Rommy Sanjaya
job_title: Software Engineer
email: contact@ardikars
description: Network Analyst
avatar: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbH_wyHENYr7LP6eFohWDOShipXov_vgkmBvf1Po4GWFxLZbki
favicon: "/favicon.ico"
twitter_handler: 
analytics_code: 
disqus: 
social_networks:
- name: facebook
  url: https://facebook.com/ardikars
- name: twitter
  url: https://twitter.com/ardikars
- name: instagram
  url: https://www.instagram.com/ardikars/
- name: google-plus
  url: 
- name: linkedin
  url: 
- name: skype
  url: 
- name: github
  url: https://github.com/ardikars
- name: codepen
  url: 
- name: stack-overflow
  url: 
- name: dribbble
  url: 
- name: behance
  url: 
- name: pinterest
  url: 
- name: tumblr
  url: 
- name: youtube
  url: 
- name: vimeo
  url: 
- name: vine
  url: 
- name: 500px
  url: 
- name: flickr
  url: 
- name: spotify
  url: 
- name: steam
  url: 
- name: wordpress
  url: 
- name: xing
  url: 
- name: bitcoin
  url: 
- name: pocket
  url: 
- name: applemusic
  url: 
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1
url: 
baseurl: 
include:
- _pages
permalink: "/:categories/:title.html"
category_dir: categories
paginate: 10
paginate_path: "/page:num/"
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
  sass_dir: assets/partials
  style: compressed
