---
title: Ardika Rommy Sanjaya
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ''
      type: posts
    values:
      comments: 'false'
encoding: UTF-8
name: Ardika Rommy Sanjaya
job_title: Software Engineer
email: contact@ardikars
description: Catatan ngopek suka2.
avatar: https://avatars0.githubusercontent.com/u/8438534?s=460&u=cee8602bcf01680f7d25da87097c933450e02e7d&v=4
favicon: "/favicon.ico"
twitter_handler:
analytics_code:
disqus:
social_networks:
  - name: twitter
    url: https://twitter.com/ardikars
  - name: github
    url: https://github.com/ardikars
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 0
show_comments: 0
show_menu: 1
fixed_sidebar: 1
url: "https://www.ardikars.com"
baseurl:
include:
  - _pages
permalink: "/post/:categories/:title.html"
category_dir: category
paginate: 5
paginate_path: "/page-:num/"
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
  sass_dir: assets/partials
  style: compressed
